//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cata
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
        public long idEvaluador { get; set; }
        public int idProduccion { get; set; }
        public int idRanking { get; set; }
    }
}
