//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlSiembra
    {
        public int id { get; set; }
        public int siembra_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
    
        public virtual siembra siembra { get; set; }
    }
}
