//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faseProduccion
    {
        public int id { get; set; }
        public int produccion_id { get; set; }
        public string nombre_fase { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual produccion produccion { get; set; }
    }
}
