//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faseProduccion
    {
        public int id { get; set; }
        public int produccion_id { get; set; }
        public string nombre_fase { get; set; }
        public string descripcion { get; set; }
    
        public virtual produccion produccion { get; set; }
    }
}
