//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siembra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siembra()
        {
            this.controlSiembras = new HashSet<controlSiembra>();
        }
    
        public int id { get; set; }
        public int parcela_id { get; set; }
        public string variedad_uva { get; set; }
        public System.DateTime fecha_siembra { get; set; }
        public string estado { get; set; }
    
        public virtual parcela parcela { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<controlSiembra> controlSiembras { get; set; }
    }
}
