//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVC_VinosCosteros.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinosCosterosEntities : DbContext
    {
        public VinosCosterosEntities()
            : base("name=VinosCosterosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<parcela> parcelas { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<siembra> siembras { get; set; }
        public virtual DbSet<controlSiembra> controlSiembras { get; set; }
        public virtual DbSet<faseProduccion> faseProduccions { get; set; }
        public virtual DbSet<cata> catas { get; set; }
        public virtual DbSet<produccion> produccions { get; set; }
    }
}
